lesson_5/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from lesson_5 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from news.views import home_page, contact_page, t_page, single_page, contact_create, advertise_page

app_name = 'news'

urlpatterns = [
    path('', home_page, name="home_page"),
    path('contact', contact_page, name='contact_page'),
    path('404-page', t_page, name='404_page'),
    path('new/<int:new_id>/', single_page, name='single_page'),
    path('contact-create', contact_create, name='contact_create'),
    path('advertise/', advertise_page, name='advertise')
]

news/models.py
from django.db import models

class AbstractBaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'
        db_table = 'contact'

class New(AbstractBaseModel):
    title = models.CharField(max_length=100)
    body = models.TextField()
    img = models.ImageField(upload_to='news/')

    def __str__(self):
        return self.title

# models.py
class Advertise(AbstractBaseModel):
    title = models.CharField(max_length=128)
    body = models.TextField()
    brand = models.CharField(max_length=128)

    class Meta:
        verbose_name = 'Advertise'
        verbose_name_plural = 'Advertises'
        db_table = 'advertise'

    def __str__(self):
        return self.title

news/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Contact, New, Advertise


# Create your views here.
def home_page(request):
    news = New.objects.all()
    return render(request, 'news/index.html', {"news": news})


def contact_page(request):
    return render(request, 'news/contact.html')

def t_page(request):
    return render(request, 'news/404.html')

def single_page(request, new_id):
    new = get_object_or_404(New, pk=new_id)
    return render(request, 'news/single_page.html', {"new": new})

def contact_create(request):
    contacts = Contact.objects.all().reverse()[:10]
    context={
        "contacts": contacts
    }

    if request.method == 'POST':
        # request.POST['email'] = request.POST['email']
        name = request.POST["name"]
        email = request.POST['email']
        message = request.POST['message']
        Contact.objects.create(name=name, email=email, message=message)

        print(request.POST)
        return redirect('news:contact_page')

        # return render(request, 'news/contact_create.html', context=context)
    else:
        return render(request, 'news/contact_create.html', context=context)

def advertise_page(request):
    advertises = Advertise.objects.all()
    return render(request, 'news/advretertise.html', {"advertises": advertises})

templates/news/advretertise.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2 class="rek">Advertisement</h2><br>
          {% for advertise in advertises %}
              <div>
              <h4>{{ advertise.brand }}</h4>
              <h3>{{ advertise.title }}</h3>
              <p>{{ advertise.body }}</p>
              </div>
          {% endfor %}
</body>
</html>

templates/news/contact.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>NewsFeed | Pages | Contact</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'news/assets/css/bootstrap.min.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'news/assets/css/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'news/assets/css/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'news/assets/css/font.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'news/assets/css/li-scroller.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'news/assets/css/slick.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'news/assets/css/jquery.fancybox.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'news/assets/css/theme.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'news/assets/css/style.css' %}">
<!--[if lt IE 9]>
<script src="{% static 'news/assets/js/html5shiv.min.js' %}"></script>
<script src="{% static 'news/assets/js/respond.min.js' %}"></script>
<![endif]-->
</head>
<body>
{#<div id="preloader">#}
{#  <div id="status">&nbsp;</div>#}
{#</div>#}
<a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
<div class="container">
  <header id="header">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="header_top">
          <div class="header_top_left">
            <ul class="top_nav">
              <li><a href="{% url 'news:home_page' %}">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="{% url 'news:contact_page' %}">Contact</a></li>
            </ul>
          </div>
          <div class="header_top_right">
            <p>Friday, December 05, 2045</p>
          </div>
        </div>
      </div>
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="header_bottom">
          <div class="logo_area"><a href="{% url 'news:home_page' %}" class="logo"><img src="{% static 'news/images/logo.jpg' %}" alt=""></a></div>
          <div class="add_banner"><a href="#"><img src="{% static 'news/images/addbanner_728x90_V1.jpg' %}" alt=""></a></div>
        </div>
      </div>
    </div>
  </header>
  <section id="navArea">
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav main_nav">
          <li class="active"><a href="{% url 'news:home_page' %}"><span class="fa fa-home desktop-home"></span><span class="mobile-show">Home</span></a></li>
          <li><a href="#">Technology</a></li>
          <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mobile</a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Android</a></li>
              <li><a href="#">Samsung</a></li>
              <li><a href="#">Nokia</a></li>
              <li><a href="#">Walton Mobile</a></li>
              <li><a href="#">Sympony</a></li>
            </ul>
          </li>
          <li><a href="#">Laptops</a></li>
          <li><a href="#">Tablets</a></li>
          <li><a href="contact.html">Contact Us</a></li>
          <li><a href="404.html">404 Page</a></li>
        </ul>
      </div>
    </nav>
  </section>
  <section id="newsSection">
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="latest_newsarea"> <span>Latest News</span>
          <ul id="ticker01" class="news_sticker">
            <li><a href="#"><img src="{% static 'news/images/news_thumbnail3.jpg' %}" alt="">My First News Item</a></li>
            <li><a href="#"><img src="{% static 'news/images/news_thumbnail3.jpg' %}" alt="">My Second News Item</a></li>
            <li><a href="#"><img src="{% static 'news/images/news_thumbnail3.jpg' %}" alt="">My Third News Item</a></li>
            <li><a href="#"><img src="{% static 'news/images/news_thumbnail3.jpg' %}" alt="">My Four News Item</a></li>
            <li><a href="#"><img src="{% static 'news/images/news_thumbnail3.jpg' %}" alt="">My Five News Item</a></li>
            <li><a href="#"><img src="{% static 'news/images/news_thumbnail3.jpg' %}" alt="">My Six News Item</a></li>
            <li><a href="#"><img src="{% static 'news/images/news_thumbnail3.jpg' %}" alt="">My Seven News Item</a></li>
            <li><a href="#"><img src="{% static 'news/images/news_thumbnail3.jpg' %}" alt="">My Eight News Item</a></li>
            <li><a href="#"><img src="{% static 'news/images/news_thumbnail2.jpg' %}" alt="">My Nine News Item</a></li>
          </ul>
          <div class="social_area">
            <ul class="social_nav">
              <li class="facebook"><a href="#"></a></li>
              <li class="twitter"><a href="#"></a></li>
              <li class="flickr"><a href="#"></a></li>
              <li class="pinterest"><a href="#"></a></li>
              <li class="googleplus"><a href="#"></a></li>
              <li class="vimeo"><a href="#"></a></li>
              <li class="youtube"><a href="#"></a></li>
              <li class="mail"><a href="#"></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="contentSection">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8">
        <div class="left_content">
          <div class="contact_area">
            <h2>Contact Us</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labolore magna aliqua. Ut enim ad minim veniam. Lorem ipsum dosectetur adipisicing elit, sed do.Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <form action="{% url 'news:contact_create' %}" class="contact_form" method="post">
                {% csrf_token %}
                <label for="name">
                    <input id="name" class="form-control" type="text" placeholder="Name*" name="name">
                </label><br>
                <label for="email">
                    <input id="email" class="form-control" type="email" placeholder="Email*" name="email">
                </label><br>
                <label for="message">
                    <textarea id="message" class="form-control" cols="30" rows="10" placeholder="Message*" name="message"></textarea>
                </label>
                <button type="submit">submit</button>
            </form>
          </div>
        </div>
      </div>
{#      <div class="col-lg-4 col-md-4 col-sm-4">#}
{#        <aside class="right_content">#}
{#          <div class="single_sidebar">#}
{#            <h2><span>Popular Post</span></h2>#}
{#            <ul class="spost_nav">#}
{#              <li>#}
{#                <div class="media"> <a href="{% url 'news:single_page' %}" class="media-left"> <img alt="" src="{% static 'news/images/post_img1.jpg' %}"> </a>#}
{#                  <div class="media-body"> <a href="{% url 'news:single_page' %}" class="catg_title"> Aliquam malesuada diam eget turpis varius 1</a> </div>#}
{#                </div>#}
{#              </li>#}
{#              <li>#}
{#                <div class="media"> <a href="{% url 'news:single_page' %}" class="media-left"> <img alt="" src="{% static 'news/images/post_img1.jpg' %}"> </a>#}
{#                  <div class="media-body"> <a href="{% url 'news:single_page' %}" class="catg_title"> Aliquam malesuada diam eget turpis varius 2</a> </div>#}
{#                </div>#}
{#              </li>#}
{#              <li>#}
{#                <div class="media"> <a href="{% url 'news:single_page' %}" class="media-left"> <img alt="" src="{% static 'news/images/post_img1.jpg' %}"> </a>#}
{#                  <div class="media-body"> <a href="{% url 'news:single_page' %}" class="catg_title"> Aliquam malesuada diam eget turpis varius 3</a> </div>#}
{#                </div>#}
{#              </li>#}
{#              <li>#}
{#                <div class="media"> <a href="{% url 'news:single_page' %}" class="media-left"> <img alt="" src="{% static 'news/images/post_img1.jpg' %}"> </a>#}
{#                  <div class="media-body"> <a href="{% url 'news:single_page' %}" class="catg_title"> Aliquam malesuada diam eget turpis varius 4</a> </div>#}
{#                </div>#}
{#              </li>#}
{#              <li>#}
{#                <div class="media"> <a href="{% url 'news:single_page' %}" class="media-left"> <img alt="" src="{% static 'news/images/post_img1.jpg' %}"> </a>#}
{#                  <div class="media-body"> <a href="{% url 'news:single_page' %} class="catg_title"> Aliquam malesuada diam eget turpis varius 2</a> </div>#}
{#                </div>#}
{#              </li>#}
{#            </ul>#}
{#          </div>#}
{#        </aside>#}
{#      </div>#}
    </div>
  </section>
  <footer id="footer">
    <div class="footer_top">
      <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="footer_widget wow fadeInLeftBig">
            <h2>Flickr Images</h2>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="footer_widget wow fadeInDown">
            <h2>Tag</h2>
            <ul class="tag_nav">
              <li><a href="#">Games</a></li>
              <li><a href="#">Sports</a></li>
              <li><a href="#">Fashion</a></li>
              <li><a href="#">Business</a></li>
              <li><a href="#">Life &amp; Style</a></li>
              <li><a href="#">Technology</a></li>
              <li><a href="#">Photo</a></li>
              <li><a href="#">Slider</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="footer_widget wow fadeInRightBig">
            <h2>Contact</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <address>
            Perfect News,1238 S . 123 St.Suite 25 Town City 3333,USA Phone: 123-326-789 Fax: 123-546-567
            </address>
          </div>
        </div>
      </div>
    </div>
    <div class="footer_bottom">
      <p class="copyright">Copyright &copy; 2045 <a href="{% url 'news:home_page' %}">NewsFeed</a></p>
      <p class="developer">Developed By Wpfreeware</p>
    </div>
  </footer>
</div>
<<script src="{% static 'news/assets/js/jquery.min.js' %}"></script> 
<script src="{% static 'news/assets/js/wow.min.js' %}"></script> 
<script src="{% static 'news/assets/js/bootstrap.min.js' %}"></script> 
<script src="{% static 'news/assets/js/slick.min.js' %}"></script> 
<script src="{% static 'news/assets/js/jquery.li-scroller.1.0.js' %}"></script> 
<script src="{% static 'news/assets/js/jquery.newsTicker.min.js' %}"></script> 
<script src="{% static 'news/assets/js/jquery.fancybox.pack.js' %}"></script> 
<script src="{% static 'news/assets/js/custom.js' %}"></script>
</body>
</html>

templates/news/contact_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .child{
            border: 2px solid #0ab20a;
            width: 400px;
            margin-bottom: 5px;
            display: flex;
            align-items: center;
        }
        ul{
            list-style: none;
        }
        h1{
            text-align: center;
            color: #0ab20a;
        }
        .ota{
            display: flex;
            justify-content: center;
            align-items: center;
        }
        body{
            background: #2f2f2f;
        }
        p{
            color: #FFFFFF;
            font-size: 20px;
            font-family: 'monospace';
        }
        
    </style>
</head>
<body>
<h1>Contacted People</h1><br>
    {% for c in contacts %}
        <div class="ota">
            <div class="child">
            <ul>
                <li>
                    <p>name: {{ c.name }}</p>
                    <p>email: {{ c.email }}</p>
                    <p>message: {{ c.message }}</p>
                </li> <br>
            </ul>
        </div>
        </div>
    {% endfor %}
</body>
</html>